name: torreyb
favicon: null
layout_spectrum: 0.35086220828816295
typography_spectrum: 0.9706377270631492
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02dedf'
    - '#ffffff'
    - '#59e8e9'
    - '#cff8f9'
    - '#81eced'
  brandStrength: 0.6875
  lightness: 0.5203441348858178
  saturation: 0.39711523498408496
  rhythmicContrast: 0.007068112259730697
purpose: []
